[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1"
serde = { version = "1", features = ["derive"] }
axum = { version = "0.7", features = ["ws"] }
tokio = { version = "1", features = ["full"] }
core = { path = "../core" }
hyper = "1.6.0"
tower-http = { version = "0.6.6", features = ["cors"] }
sea-orm = { version = "1", features = ["sqlx-sqlite", "runtime-tokio-rustls"] }
serde_json = "1"
futures-util = "0.3"
chrono = { version = "0.4", default-features = false, features = [
  "clock",
  "std",
] }
