version: "3"
name: fibbelous
services:
  fibbelous:
    image: maartenv/fibbelous
    container_name: fibbelous
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    restart: unless-stopped
    volumes:
      - data:/app/.data
    expose:
      - 8080
    networks:
      - proxy

networks:
    proxy:
      external: true

volumes:
  data:
