import { Page } from "../models";

export const pages: Page[] = [
  {
    id: "1",
    created: Date.now(),
    icon: "🤗",
    title: "Page 1",
    parent: null,
    content: `# Page 1`,
  },
  {
    id: "1.1",
    created: Date.now(),
    icon: "🤗",
    title: "Page 1.1",
    parent: "1",
    content: `# Page 1.1`,
  },
  {
    id: "1.1.1",
    created: Date.now(),
    icon: "🤗",
    title: "Page 1.1.1",
    parent: "1.1",
    content: `# Page 1.1.1`,
  },
  {
    id: "1.1.1.1",
    created: Date.now(),
    title: "Page 1.1.1.1",
    icon: "🤗",
    parent: "1.1.1",
    content: `# Page 1.1.1.1`,
  },
  {
    id: "1.2",
    created: Date.now(),
    title: "Page 1.2",
    parent: "1",
    content: `# Page 1.2`,
  },
  {
    id: "2",
    created: Date.now(),
    icon: "🤗",
    title: "Page 2",
    parent: null,
    content: `# Page 2`,
  },
  {
    id: "2.1",
    created: Date.now(),
    icon: "🤗",
    title: "Page 2.1",
    parent: "2",
    content: `# Page 2.1`,
  },
  {
    id: "2.1.1",
    created: Date.now(),
    icon: "🤗",
    title: "Page 2.1.1",
    parent: "2.1",
    content: `# Page 2.1.1`,
  },
  {
    id: "2.1.1.1",
    created: Date.now(),
    title: "Page 2.1.1.1",
    icon: "🤗",
    parent: "2.1.1",
    content: `# Page 2.1.1.1`,
  },
  {
    id: "2.2",
    created: Date.now(),
    title: "Page 2.2",
    parent: "2",
    content: `# Page 2.2`,
  },
];
